version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products.API/Dockerfile
    ports:
      - 32768:80
      - 32769:443
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db-password
    ports:
      - 5432:5432