version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Products.API/Dockerfile
    ports:
      - 32768:80

  onlinebookstore.mvc:
    image: ${DOCKER_REGISTRY-}onlinebookstoremvc
    build:
      context: .
      dockerfile: OnlineBookstore.MVC/Dockerfile
    ports:
      - 32769:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432